apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo-grafana.yaml
  - helmrepo-prometheus-community.yaml
  - o11y.yaml
  - loki.yaml
  - mimir.yaml
  - kube-state-metrics.yaml
  - alloy.yaml
  - grafana.yaml
  - scrutiny.yaml
  - scrutiny-influxdb.yaml
  - helmrepo-influxdata.yaml
  - homebridge.yaml
  - media.yaml
  - spoolman.yaml
