---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metrics
  namespace: o11y
  annotations:
    external-dns.alpha.kubernetes.io/expose: "true"
    external-dns.alpha.kubernetes.io/target: traefik.i.recompiled.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`metrics.i.recompiled.org`)
      kind: Rule
      services:
        - name: mimir-gateway
          port: 8080
  tls:
    secretName: metrics-tls
