---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seaweedfs-ui-https
  namespace: seaweedfs
  annotations:
    external-dns.alpha.kubernetes.io/expose: "true"
    external-dns.alpha.kubernetes.io/target: traefik.i.recompiled.org
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`seaweedfs.i.recompiled.org`)
      services:
        - name: seaweedfs-admin-ui
          port: 23646
  tls:
    secretName: seaweedfs-tls
