apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - s3-credentials-secret.yaml
  - s3-ingressroute.yaml
  - s3-tls-cert.yaml
  - vpa.yaml
  # Admin UI
  - admin-ui-secret.yaml
  - admin-ui-deployment.yaml
  - admin-ui-tls-cert.yaml
  - admin-ui-ingressroute.yaml
