---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seaweedfs-s3-https
  namespace: seaweedfs
  annotations:
    external-dns.alpha.kubernetes.io/expose: "true"
    external-dns.alpha.kubernetes.io/target: traefik.i.recompiled.org
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`s3.i.recompiled.org`)
      services:
        - name: seaweedfs-filer
          port: 8333  # S3 port on filer
  tls:
    secretName: s3-tls
